language: php

php:
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer update --dev --prefer-source --no-interaction
  - export APP_ENV=testing
  - touch storage/testing.sqlite

script: vendor/bin/phpunit