language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer install --dev --prefer-source --no-interaction
  - export APP_ENV=testing
  - touch storage/testing.sqlite
  - chmod 777 -R public/

script: vendor/bin/phpspec run